language: python
python: 2.7
env:
  - TOX_ENV=py26-dj14
  - TOX_ENV=py26-dj15
  - TOX_ENV=py26-dj16
  - TOX_ENV=py27-dj14
  - TOX_ENV=py27-dj15
  - TOX_ENV=py27-dj16
  - TOX_ENV=py33-dj16
  - TOX_ENV=flake8
script:
  - tox -e $TOX_ENV
install:
  - pip install tox
