language: python
python: 2.7
env:
  - TOXENV=py26-dj14
  - TOXENV=py26-dj15
  - TOXENV=py26-dj16
  - TOXENV=py27-dj14
  - TOXENV=py27-dj15
  - TOXENV=py27-dj16
  - TOXENV=py33-dj16
  - TOXENV=py34-dj16
  - TOXENV=flake8
  - TOXENV=coverage
script:
  - tox
before_install:
  - sudo apt-get update
  - sudo apt-get install python3.4 python3.4-dev
install:
  - pip install tox
