sudo: false
language: python
python: 3.5
env:
  - TOXENV=py27-dj18
  - TOXENV=py27-dj19
  - TOXENV=py27-dj110
  - TOXENV=py34-dj18
  - TOXENV=py34-dj19
  - TOXENV=py34-dj110
  - TOXENV=py35-dj19
  - TOXENV=py35-dj110
  - TOXENV=flake8
  - TOXENV=coverage
script:
  - tox
install:
  - pip install tox
