language: python
python: 2.7
env:
  - TOXENV=py26-dj14
  - TOXENV=py26-dj15
  - TOXENV=py26-dj16
  - TOXENV=py27-dj14
  - TOXENV=py27-dj15
  - TOXENV=py27-dj16
  - TOXENV=py27-dj17
  - TOXENV=py33-dj16
  - TOXENV=py34-dj16
  - TOXENV=py34-dj17
  - TOXENV=flake8
  - TOXENV=coverage
script:
  - tox
install:
  - pip install tox
